<?php $this->partial("shared/banner"); ?>
<div id="login-form">
    <h2>Sign up using this form</h2>
    <?php echo $this->tag->form("signup/register"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name") ?>
        <span class="error"><?php echo $nameError;?></span>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email") ?>
        <span class="error"><?php echo $emailError;?></span>
    </p>
    
    <p>
        <label for="password">password</label>
        <?php echo $this->tag->passwordField("password") ?>
        <span class="error"><?php echo $passwordError;?></span>
    </p>

    <p>
        <label for="password_confirm">Password-Confirm</label>
        <?php echo $this->tag->passwordField("password_confirm") ?>
        <span class="error"><?php echo $password_confirmError;?></span>
    </p>
    <p>
        <label for="validate_code">Validate-Code</label>
        <img id="code" class="validate_code"  src="/validatecode/flush" onclick="this.src='/validatecode/flush?'+Math.random()"/>
        <?php echo $this->tag->textField("validate_code") ?>
        <span class="error"><?php echo $validate_codeError;?></span>
    </p>
    <p>
        <?php echo $this->tag->submitButton("Register") ?>
    </p>

</form>
</div>

<?php $this->partial("shared/copyright"); ?>

