{{partial('admin/devision_header')}}
{{stylesheetLink("css/default.css")}}
{{javascriptInclude("js/jquery-1.9.0.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/vendor/jquery.ui.widget.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/tmpl.min.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/load-image.all.min.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/canvas-to-blob.min.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/bootstrap.min.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/jquery.blueimp-gallery.min.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/jquery.iframe-transport.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/jquery.fileupload.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/jquery.fileupload-process.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/jquery.fileupload-image.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/jquery.fileupload-audio.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/jquery.fileupload-video.js")}}
{{javascriptInclude("js/jQuery-File-Upload-9.12.1/js/jquery.fileupload-validate.js")}}
<div class="rightContent">
    <h3>添加游戏  <span class="success"><?php if (isset($sucessMessage)) {
    echo $sucessMessage;
} ?></span></h3>
    {{form("admin/gamesadd") }}
    <p>
        <label for="gameBigCategoryId">游戏分类：</label>
        {{selectStatic("gameBigCategoryId", gameBigCategorys) }}   
        <label for="gameCategoryId">游戏类型：</label>
        {{selectStatic("gameCategoryId", gameCategorys) }}
        <label for="gameCategoryId">游戏题材：</label>
        {{selectStatic("gameStyleId", gameStyles) }}
    </p>
    <p>
        <label for="gameName">游戏名称：</label>
        {{textField("gameName") }}
        <span class="error"><?php echo isset($gameNameError) ? $gameNameError : ''; ?></span>
    </p>
    <p>
        <label for="preCharacter">游戏名称-拼音头字母：</label>
        {{textField("preCharacter") }}
        <span class="error"><?php echo isset($preCharacterError) ? $preCharacterError : ''; ?></span>
    </p>
    <p>
        <label for="preCharacter">游戏图片：</label>
<?php echo $this->tag->fileField(array('name' => "imgs[]", "id" => 'imgUpload')) ?>
        <span class="error"><?php //echo isset($preCharacterError) ? $preCharacterError : '';  ?></span>
        {{hiddenField('imgids')}}
    <ul id="img-list">
    </ul>
    <div class="clearBoth"></div>
</p>
<p>
    <label for="preCharacter">游戏视频：</label>
<?php echo $this->tag->textField(array("video", 'size' => 100)) ?>
    <span class="error"><?php //echo isset($preCharacterError) ? $preCharacterError : '';  ?></span>
</p>
<div>
    <ul id="img-list"></ul>
    <div class="clearBoth"></div>
</div>
<p>
    <label for="developCompany">开发公司：</label>
    {{textField('developCompany') }}
    <span class="error"><?php echo isset($developCompanyError) ? $developCompanyError : ''; ?></span>
</p>
<p>
    <label for="startRunTime">开始运营时间：</label>
    {{dateField("startRunTime") }}
</p>
<p>
    <label for="whichD">游戏画面：</label>
<?php echo $this->tag->selectStatic("whichD", ["2D" => "2D", "2.5D" => "2.5D", "3D" => "3D"]) ?>
</p>
<p>
    <label for="intro">游戏介绍：</label><span class="error"><?php echo isset($introError) ? $introError : ''; ?></span>
    <br>
<?php echo $this->tag->textArea(array("intro", "cols" => 70, "rows" => 10)) ?>
</p>
<p>
    {{submitButton("添加") }}
</p>
</div>
<script>
    $(function () {
        'use strict';

        $('#imgUpload').fileupload({
            url: '/file/imgupload',
            dataType: 'json',
            acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
            autoUpload: true,
            sequentialUploads: true,
            done: function (e, data) {
                $.each(data.result.files, function (index, file) {
                    ("#img-list").html('<li class="thumb-item"><img src="' + file.thumbnailUrl + '"></li>');
                    $('input[name="imgids"]').val(file.imgId);
                });
                
            }
        });

    });
</script>
