<?php $this->partial("shared/banner"); ?>
{{javascriptInclude('js/jquery.js')}}
<div class="container">
<h1>{{userinfo['name']}}的主页</h1>
    <a href="/team/add">
        创建战队
    </a> 

<div>
    <a href="/user/followers?id={{userinfo['userId']}}">followers({{followers}})</a> |
    <a href="/user/followings?id={{userinfo['userId']}}">followings({{followings}})</a>
</div>


<h3>我的好友</h3>
{%if myfs %}
<ul>
  {%for f in myfs %}
  <li>
    <a href="/user/detail?name={{f['name']}}" target="_blank">{{f['name']}}</a>
    <button onclick="unfollow({{f['userId']}})">取消关注</button>
  </li>
  {%endfor%}
</ul>
{%endif%}
</div>
<?php $this->partial("shared/footer"); ?>

