<?php $this->partial("shared/banner"); ?>
<div class="container">
<h1>{{userinfo['name']}}的主页</h1>
<h3>好友申请</h3>
{%if fapplys %}
<ul>
  {%for apply in fapplys %}
  <li><a href="/user/detail?name={{apply['userName']}}" target="_blank">{{apply['userName']}}</a><button onclick="passApply({{apply['id']}})">通过</button></li>
  {%endfor%}
</ul>
{%endif%}
</div>

<h3>我的好友</h3>
{%if myfs %}
<ul>
  {%for f in myfs %}
  <li><a href="/user/detail?name={{f['userName']}}" target="_blank">{{f['userName']}}</a></li>
  {%endfor%}
</ul>
{%endif%}
</div>
<script>
    function passApply(rid){
       $.ajax({
            url:'/user/passfriend',
            type:'post',
            data:{id:rid},
            dataType:'json',
            success:function(re){
                if(re.status==500)
                    alert(re.message);
            }
            
        }); 
    }
    function addFriend(userId){
        $.ajax({
            url:'/user/addfriend',
            type:'post',
            data:{friendId:userId},
            dataType:'json',
            success:function(re){
                if(re.status==500)
                    alert(re.message);
                else
                    history.go(0);
            }
            
        });
    }
</script>
<?php $this->partial("shared/copyright"); ?>

