<?php $this->partial("shared/banner"); ?>
{{javascriptInclude('js/jquery-1.9.0.js')}}
{{javascriptInclude('js/layer/layer.js')}}
<div class="container">
<h1>{{userinfo['name']}}的主页</h1>
{%if userId!=userinfo['userId']%}
{%if userName %}
    {%if followed %}
    <button onclick="unfollow({{userinfo['userId']}})" id="unfollow"  class="applyBtn">
        取消关注
    </button>
    {%else%}
    <button onclick="follow({{userinfo['userId']}})" id="follow">关注</button>
    {%endif%}
{%else%}
    <button onclick="follow({{userinfo['userId']}})">关注</button>
{%endif%}
{%endif%}
</div>
<script>
    
    </script>
<?php $this->partial("shared/footer"); ?>

